# Copyright 2017 AT&T Intellectual Property.  All other rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

release_group: null

images:
  tags:
    anchor: gcr.io/google_containers/hyperkube-amd64:v1.10.2
    controller_manager: gcr.io/google_containers/hyperkube-amd64:v1.10.2
  pull_policy: "IfNotPresent"

labels:
  controller_manager:
    node_selector_key: kubernetes-controller-manager
    node_selector_value: enabled

anchor:
  dns_policy: Default
  kubelet:
    manifest_path: /etc/kubernetes/manifests
  period: 15
  files_to_copy:
    - source: /configmap/cluster-ca.pem
      dest: /etc/kubernetes/controller-manager/cluster-ca.pem
    - source: /configmap/controller-manager.pem
      dest: /etc/kubernetes/controller-manager/controller-manager.pem
    - source: /configmap/kubeconfig.yaml
      dest: /etc/kubernetes/controller-manager/kubeconfig.yaml
    - source: /secret/controller-manager-key.pem
      dest: /etc/kubernetes/controller-manager/controller-manager-key.pem
    - source: /secret/service-account.priv
      dest: /etc/kubernetes/controller-manager/service-account.priv
    - source: /configmap/kubernetes-controller-manager.yaml
      dest: /etc/kubernetes/manifests/kubernetes-controller-manager.yaml

controller_manager:
  host_etc_path: /etc/kubernetes/controller-manager

command_prefix:
  - /controller-manager
  - --cluster-cidr=10.97.0.0/16
  - --node-monitor-period=5s
  - --node-monitor-grace-period=20s
  - --pod-eviction-timeout=60s
  - --service-cluster-ip-range=10.96.0.0/16
  - --terminated-pod-gc-threshold=1000

secrets:
  tls:
    ca: placeholder
    cert: placeholder
    key: placeholder
  service_account:
    private_key: placeholder

network:
  kubernetes_netloc: 10.96.0.1
  pod_cidr: 10.97.0.0/16
  service_cidr: 10.96.0.0/16
  kubernetes_controller_manager:
    port: 10252

service:
  name: kubernetes-controller-manager

dependencies:
  controller_manager:

pod:
  mounts:
    controller_manager:
      init_container: null
      controller_manager:
  lifecycle:
    upgrades:
      daemonsets:
        pod_replacement_strategy: RollingUpdate
        controller_manager:
          enabled: false
          min_ready_seconds: 0
          max_unavailable: 1
    termination_grace_period:
      controller_manager:
        timeout: 3600
  resources:
    enabled: false
    controller_manager:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    anchor_pod:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
manifests:
  configmap_bin: true
  configmap_etc: true
  controller_manager: true
  secret: true
