{{/*
Copyright 2018 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- if .Values.manifests.deployment }}
{{- $envAll := . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-keystone-webhook
  labels:
{{ tuple $envAll "kubernetes-keystone-webhook" "api" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 4 }}
spec:
  replicas: {{ $envAll.Values.pod.replicas.api }}
  selector:
    matchLabels:
{{ tuple $envAll "kubernetes-keystone-webhook" "api" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 6 }}
  template:
    metadata:
      labels:
{{ tuple $envAll "kubernetes-keystone-webhook" "api" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.utils.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.utils.hash" }}
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: apiserver
          image: {{ .Values.images.tags.apiserver }}
{{ tuple $envAll $envAll.Values.pod.resources.kubernetes_apiserver | include "helm-toolkit.snippets.kubernetes_resources" | indent 6 }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

          command:
            {{- range .Values.command_prefix }}
            - {{ . }}
            {{- end }}
            - --authorization-mode=Webhook
            - --advertise-address=$(POD_IP)
            - --anonymous-auth=false
            - --endpoint-reconciler-type=none
            - --bind-address=0.0.0.0
            - --secure-port={{ .Values.network.kubernetes_apiserver.port }}
            - --insecure-port=0
            - --client-ca-file=/etc/kubernetes/apiserver/pki/cluster-ca.pem
            - --tls-cert-file=/etc/kubernetes/apiserver/pki/apiserver.pem
            - --tls-private-key-file=/etc/kubernetes/apiserver/pki/apiserver-key.pem
            - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
            - --kubelet-certificate-authority=/etc/kubernetes/apiserver/pki/cluster-ca.pem
            - --kubelet-client-certificate=/etc/kubernetes/apiserver/pki/apiserver.pem
            - --kubelet-client-key=/etc/kubernetes/apiserver/pki/apiserver-key.pem
            - --etcd-servers={{ tuple "etcd" "internal" "client" . | include "helm-toolkit.endpoints.keystone_endpoint_uri_lookup" }}
            - --etcd-cafile=/etc/kubernetes/apiserver/pki/etcd-client-ca.pem
            - --etcd-certfile=/etc/kubernetes/apiserver/pki/etcd-client.pem
            - --etcd-keyfile=/etc/kubernetes/apiserver/pki/etcd-client-key.pem
            - --allow-privileged=true
            - --service-account-key-file=/etc/kubernetes/apiserver/pki/service-account.pub
            - --authentication-token-webhook-config-file=/etc/kubernetes/apiserver/webhook.kubeconfig
            - --authorization-webhook-config-file=/etc/kubernetes/apiserver/webhook.kubeconfig
          ports:
            - containerPort: {{ .Values.network.kubernetes_apiserver.port }}
          readinessProbe:
            tcpSocket:
              port: 6443
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 6443
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: etc
              mountPath: /etc/kubernetes/apiserver
            - name: {{ .Values.service.name }}-etc
              mountPath: /etc/kubernetes/apiserver/webhook.kubeconfig
              subPath: webhook.kubeconfig
              readOnly: true
        - name: kubernetes-keystone-webhook
{{ tuple $envAll "kubernetes_keystone_webhook" | include "helm-toolkit.snippets.image" | indent 10 }}
{{ tuple $envAll $envAll.Values.pod.resources.server | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          command:
            - /tmp/webhook_start.sh
          volumeMounts:
            - name: etc-kubernetes-keystone-webhook
              mountPath: /etc/kubernetes-keystone-webhook
            - name: key-kubernetes-keystone-webhook
              mountPath: /opt/kubernetes-keystone-webhook/pki/tls.crt
              subPath: tls.crt
              readOnly: true
            - name: key-kubernetes-keystone-webhook
              mountPath: /opt/kubernetes-keystone-webhook/pki/tls.key
              subPath: tls.key
              readOnly: true
            - name: {{ .Values.service.name }}-etc
              mountPath: /etc/kubernetes-keystone-webhook/policy.json
              subPath: policy.json
              readOnly: true
            - name: {{ .Values.service.name }}-bin
              mountPath: /tmp/webhook_start.sh
              subPath: webhook_start.sh
              readOnly: true
      volumes:
        - name: etc
          hostPath:
            path: {{ .Values.apiserver.host_etc_path }}
        - name: etc-kubernetes-keystone-webhook
          emptyDir: {}
        - name: key-kubernetes-keystone-webhook
          secret:
            secretName: {{ $envAll.Values.secrets.certificates.api }}
            defaultMode: 0444
        - name: {{ .Values.service.name }}-etc
          configMap:
            name: {{ .Values.service.name }}-etc
            defaultMode: 0444
        - name: {{ .Values.service.name }}-bin
          configMap:
            name: {{ .Values.service.name }}-bin
            defaultMode: 0555
{{- end }}
